site_name: BudgetManager Documentation
site_description: A simple CLI tool to manage personal finances
site_author: RealNamison
repo_name: GitHub
repo_url: https://github.com/RealNamison/budgetmanager

docs_dir: docs

nav:
  - Home: index.md
  - Quick Start: index.md#quick-start
  - Installation: index.md#installation
  - CLI Commands: index.md#cli-commands
  - Configuration: index.md#configuration
  - Data Storage: index.md#data-storage
  - Reporting & Charts: index.md#reporting--charts
  - Testing: index.md#testing
  - License: index.md#license
  - FAQ: index.md#faq
  - Troubleshooting: index.md#troubleshooting

theme:
  name: material
  language: en

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.superfences

plugins:
  - search