site_name: BudgetManager
site_description: Documentation for BudgetManager, a CLI tool for personal finance management.
docs_dir: docs

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - Reports: reports.md
  - Project Structure: project_structure.txt
  - Quickstart: quickstart.ipynb

theme:
  name: mkdocs
  # Customization can be added here, such as palette or font

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
